### ISSUE TITLE
Create Vagrant for local development

### ISSUE THREAD

**Issue by chrisdl** [nehalm/NY-PY#6]
I'm on the case. This will entail adding some info to readme.md so that everyone will understand how to set it up.

**Comment by gabekneisley** [comment]
Sorry, I hit the close button as in 'close this window and stop editing'. Re-opening...

**Comment by afonsecadotorg** [comment]
What OS are we using?

I will suggest just to push the vagrant file once is configured so everyone' development environment is equal.

I used ubuntu 12.04 lts 32 bits + virtualbox.

Are we using virtualenv?

**Comment by chrisdl** [comment]
yeah ubuntu box would be my recommendation. The one I usually use it precise64, but we could do precise32 if you want 32 bit for some reason.

**Comment by afonsecadotorg** [comment]
we can use 64...I have a provision that install Git , virtual env, django automatically. We push vagrant config file and no one has to worry about setups no more.

**Comment by chrisdl** [comment]
ah ok, I've included a setup.sh in vagrant/setup.sh give it a look over and replace it with your setup. Does it automatically setup a DB? Also, a virtualenv (wrapped or no) is only really needed on host machine not on the vagrant (since it is already isolated).

**Comment by chrisdl** [comment]
Alright pushed branch to github. it works well enough for me, but I didn't add DB creation or anything like that (I guess we only need to download sqlite3 on vagrant box if we are using that locally?), so will require 1 or 2 more commits before merge with master I reckon.

**Comment by gabekneisley** [comment]
We need to get the DB question answered. Since we're using vagrant, why don't we just use Postgres in development and production? Then we don't have to worry about SQL inconsistencies if we ever have to compose statements.

**Comment by chrisdl** [comment]
Postgres would be fine with me, that is the only database i am familiar with for django anyway.

**Comment by afonsecadotorg** [comment]
SQLlite comes with django Postgres works well with Heroku but require some lite setup at first but if we use Vagrant then it will not be a bump.

If we are going to use Heroku for Production, then we should consider  making our Vagrant Dev box equal to Heroku Prod. 

I believe Heroku uses virtualEnv too.

So we should have something like this:

Python 2.7.x
django 1.5
virtual env 
postgres
git

anything else?

**Comment by chrisdl** [comment]
I was under the impression that we were gonna use the EC2 that Sid set up for production. Virtualenv is just to get get a separate python env for your local box, since we are already isolating the dev environment with Vagrant I am not sure we need a virtual environment inside the vagrant box as well (this is getting meta very quickly haha).

**Comment by gabekneisley** [comment]
Well, I think the idea was that we would run on a naked EC2 instance rather than heroku. We threw around a lot of ideas. Let's keep our eye on minimum headache. Here is what I remember from the meetup:

### Heroku

Benefits: 
- it's easy and we all know it
- it's free to develop and cheap to deploy
- we don't have to worry much about security on the OS level, just the app level.

Drawbacks:
- Has been a pain in the ass for several of us to get up and running.
- No file system access, which forces us to go EC2 just to let someone upload a single photo. Also, doesn't always play nice with django statics collection out of the box

Notes:
- I'm using a free postgres add-on for my project. It requires a credit card, but it is a free tier.
- The drawbacks are mitigated by expertise, not necessarily system limitations.

### EC2

Benefits:
- We do whatever the hell we want.

Drawbacks:
- We don't have a dedicated sysop, which means that we have to draft someone (like @chrisdl @sid99 or @afonsecadotorg ) who may have just wanted to code to be the dev ops person every time something goes wrong.
- I don't know what I don't know about OS level security. I _do_ know that we'll need help with keys, and, speaking for myself, as a developer, I'm more likely to set things up like a dev box than a production box, simply because that's what I know.
- We pay for all usage, not just production.

**Comment by afonsecadotorg** [comment]
I think regardless of EC2 or Heroku, we need our Dev sort out first. It takes some time to do this non-coding ground work but it makes us have the identical dev environment and it makes new comers very productive later on.

I do agree with @chrisdl about Vagrant and virtualEnv redundancy. What It did make sense from a team I'm working on is that we can have/switch/test different system environment very easily when upgrading packages. We don't need to alter the virtual machine itself.

It seems Vagrant, Git, Django and Postgres is the way to go so if we agree with this what is the next action?

**Comment by chrisdl** [comment]
@afonsecadotorg That is a fair comment about virtualenv on the vagrant, hadn't actually thought of that use-case.

I'll add a bash-script for installing postgres on the vagrant to be run after installation of the vagrant.

**Comment by afonsecadotorg** [comment]
@chrisdl  I don't see the setup.sh in the repo.

@nehalm  Upload a readme file, lets try to create  a provision that follow his suggestion  so when the a developer start vagrant for the first time, it will automatically created/install dependencies for them in his distro. We can also redistribute the VM image but in the long run is a bit hard to maintain it specially with newer dependencies. 

So lets start with the basic...the distro!
I guess ubuntu is the choice. You can run a 64 bit machine on a 32 bit host but there is some caveats on that and it some cases you can't.

My machine is 64 bit and I can run either but there might be team members with 32 bit support only.

any suggestion?

**Comment by gabekneisley** [comment]
I think we better stick to 32 bit. Before anything, this is a community project. @katychuang was talking about letting some beginners work with us. Let's be friendly to older Windows machines, and those stuck coding on them ;)

**Comment by afonsecadotorg** [comment]
I always be a beginner =)

ubuntu 12.10 32 bit:

http://files.vagrantup.com/precise32.box

Good to go?

There is Chef and Puppet but for now a good ol' script is just fine for now with all the setup done for us... agreed?

**Comment by chrisdl** [comment]
I've got it just about done, just testing to see if it works now. will push in a couple of minutes.
If everyone thinks it looks good we can do the merge now that it works I reckon.

**Comment by afonsecadotorg** [comment]
Sounds great... I have personal simple script that we can tweak too.. I think it will be great to make the dev standard.

I have some issues with the code because my django version is newer:
vagrant@precise32:~/src/ny-py$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/**init**.py", line 429, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/**init**.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/**init**.py", line 252, in fetch_command
    app_name = get_commands()[subcommand]
  File "/usr/lib/python2.7/dist-packages/django/core/management/**init**.py", line 101, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/lib/python2.7/dist-packages/django/utils/functional.py", line 276, in **getattr**
    self._setup()
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 139, in **init**
    logging_config_func(self.LOGGING)
  File "/usr/lib/python2.7/logging/config.py", line 777, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 562, in configure
    'filter %r: %s' % (name, e))
ValueError: Unable to configure filter 'require_debug_false': Cannot resolve 'django.utils.log.RequireDebugFalse': No module named RequireDebugFalse

it got fixed after I removed some packages but it will be better to have one dev system

-)

Let me know how is it going

**Comment by chrisdl** [comment]
Pushed final a while ago. Haven't included virtualenv on the vagrant box yet though, so you can do that if you want. Instructions for getting the vagrant going are in the README.md

**Comment by chrisdl** [comment]
So try to install the vagrant, and if you don't have isses lets merge it into master branch i guess? @gabekneisley @afonsecadotorg @nehalm

**Comment by chrisdl** [comment]
closing this issue due to it being ancient.
